---
version: '2.1'

services:
  webserver:
    build: .
    restart: unless-stopped
    volumes:
      - ./config.inc.php:/var/www/html/config/config.inc.php
    ports:
      - "8080:80"
    networks:
      - app-net
  mysql:
    image: mysql:5.6
    container_name: mysql
    hostname: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql_data: {}
