---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: Linux


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:

  # Runs on master Branch and Tags
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+*'


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  smoke_linux:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"

    name: "[PHP ${{ matrix.php }}]"
    steps:

      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Show environment
        shell: bash
        run: |
          env

      - name: Show network
        shell: bash
        run: |
          netstat -an || true
          ss -tlun || true

      - name: Show Docker version
        shell: bash
        run: |
          docker version

      # ------------------------------------------------------------
      # Setup
      # ------------------------------------------------------------
      - name: Configure
        shell: bash
        run: |
          cp .env-example .env
          echo "PHP_VERSION=${PHP}" >> .env
        env:
          PHP: ${{ matrix.php }}

      # ------------------------------------------------------------
      # Build & Run
      # ------------------------------------------------------------
      - name: Build
        shell: bash
        run: |
          retry() {
            for n in $(seq ${RETRIES}); do
              echo "[${n}/${RETRIES}] ${*}";
              if eval "${*}"; then
                echo "[SUCC] ${n}/${RETRIES}";
                return 0;
              fi;
              sleep 2;
              echo "[FAIL] ${n}/${RETRIES}";
            done;
            return 1;
          }
          retry make build
        env:
          RETRIES: 20

      - name: Run
        shell: bash
        run: |
          retry() {
            for n in $(seq ${RETRIES}); do
              echo "[${n}/${RETRIES}] ${*}";
              if eval "${*}"; then
                echo "[SUCC] ${n}/${RETRIES}";
                return 0;
              fi;
              sleep 2;
              echo "[FAIL] ${n}/${RETRIES}";
            done;
            return 1;
          }
          retry make start
        env:
          RETRIES: 20

      # ------------------------------------------------------------
      # Wait
      # ------------------------------------------------------------
      - name: Wait
        shell: bash
        run: |
          sleep 10

      # ------------------------------------------------------------
      # Test
      # ------------------------------------------------------------
      - name: Test
        shell: bash
        run: |
          SUCCESS=0
          for i in $(seq 60); do
            printf "."
            if [ "$(curl -sS -o /dev/null -w '%{http_code}' http://localhost:8000/login.php)" = "200" ]; then
              SUCCESS=1;
              break;
            fi
            sleep 1;
          done
          if [ "${SUCCESS}" != "1" ]; then
            printf "\\nFAILED"
            false
          else
            printf "\\nSUCCESS"
          fi
